{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "7dfb375f_f2599a5a",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1511722
      },
      "writtenOn": "2022-09-27T14:24:33Z",
      "side": 1,
      "message": "If that\u0027s the case, should we be logging these errors in the first place?",
      "revId": "02c848f2add3486c4ef5f401728b22edd6654b32",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}